/* src/include/linux/mapi/config.h.  Generated by configure.  */
/* config.in.  Generated from configure.ac by autoheader.  */

/* Name of package */
#define PACKAGE "mapi"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "xinidis@csd.uoc.gr"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Monitoring API"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Monitoring API 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "monitoring-api"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Version number of package */
#define VERSION "0.0.1"

/* Define to empty if `const' does not conform to ANSI C. */
/* #undef const */

/* Define as `__inline' if that's what the C compiler calls it, or to nothing
   if it is not supported. */
/* #undef inline */
